### ISSUE TITLE
StaticAssert.h:32:40: error: static assertion failed

### ISSUE THREAD

**Issue by mictas** [ros-planning/moveit#1906]
Hello,

I'm working on Ubuntu 16.04 LTS with ROS Kinetic.
I want to use a "3DConnexion SpaceMouse Module USB" to move an our robotic arm (6 axes).
I added the package "moveit_jog_arm" into its workspace, but when I compile (using catkin_make) the following error occurrs twice:

/usr/include/eigen3/Eigen/src/Core/util/StaticAssert.h:32:40: error: static assertion failed: YOU_PERFORMED_AN_INVALID_TRANSFORMATION_CONVERSION
     #define EIGEN_STATIC_ASSERT(X,MSG) static_assert(X,#MSG);

I've searched a solution in the web but I haven't solved the problem.
Could someone help me?
Thank you.

**Comment by rhaschke** [comment]
moveit_jog_arm was added to the master branch only (in #1360). Because there are many other changes to the master branch, which jog_arm relies on, you need to [build the full master branch of MoveIt from source](https://ros-planning.github.io/moveit_tutorials/doc/getting_started/getting_started.html). You cannot just pick a single package. You will also need a recent version of t[f2](https://github.com/ros/geometry2) in your catkin workspace.
