### PR TITLE
Fix macro name

### PR DESCRIPTION
**Pull request by mikaelarguedas**
Fix gcc warning introduced in #535

### CODE REVIEW

**Comment by v4hn** [comment]
Thanks @mikaelarguedas !

Do you have any idea why my `catkin_make` fails to print the warning?

**Comment by mikaelarguedas** [comment]
I originally noticed it on the dev jobs that use `catkin_make_isolated` but successfully reproduced it with `catkin_make` locally:
```
$ catkin_make > /dev/null
moveit_core: You did not request a specific build type: Choosing 'Release' for maximum performance
In file included from /opt/ros/kinetic/include/ros/ros.h:40:0,
                 from /home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/planning_scene_monitor/include/moveit/planning_scene_monitor/planning_scene_monitor.h:40,
                 from /home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_representation.h:40,
                 from /home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/plan_execution/include/moveit/plan_execution/plan_execution.h:41,
                 from /home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/plan_execution/src/plan_execution.cpp:37:
/home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/plan_execution/src/plan_execution.cpp: In member function ‘void plan_execution::PlanExecution::successfulTrajectorySegmentExecution(const plan_execution::ExecutableMotionPlan*, std::size_t)’:
/opt/ros/kinetic/include/ros/console.h:346:176: warning: too many arguments for format [-Wformat-extra-args]
     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
                                                                                                                                                                                ^
/opt/ros/kinetic/include/ros/console.h:349:5: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER’
     ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER(0, __VA_ARGS__)
     ^
/opt/ros/kinetic/include/ros/console.h:379:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION’
       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
       ^
/opt/ros/kinetic/include/ros/console.h:561:35: note: in expansion of macro ‘ROS_LOG_COND’
 #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
                                   ^
/opt/ros/kinetic/include/rosconsole/macros_generated.h:214:24: note: in expansion of macro ‘ROS_LOG’
 #define ROS_ERROR(...) ROS_LOG(::ros::console::levels::Error, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
                        ^
/home/mikael/work/ros/moveit_ws/src/moveit/moveit_ros/planning/plan_execution/src/plan_execution.cpp:495:7: note: in expansion of macro ‘ROS_ERROR’
       ROS_ERROR("plan_execution", "Execution of path-completion side-effect failed. Preempting.");

```

Maybe you missed the warning buried in the middle of all the stdout when you built it ?
